### ISSUE TITLE
Logo, Search, and Block Hero Annotations Not working

### ISSUE THREAD

**Issue by justinlevi** [pattern-lab/starterkit-mustache-demo#2]
the el selectors don't seem to correlate to the pattern html. PR issued. 

https://github.com/pattern-lab/starterkit-mustache-demo/pull/1

**Comment by dmolsen** [comment]
@justinlevi -

Great catch. I'll merge this to `dev` tonight on my local machine and push out an update. We really appreciate the PR.

**Comment by dmolsen** [comment]
This has been merged and `v4.0.1` of the demo has been released.
