### ISSUE TITLE
ToutList? 

### ISSUE THREAD

**Issue by justinlevi** [pattern-lab/starterkit-mustache-demo#6]
This is probably a silly question, but what on earth does "Tout" stand for? I've realize it's an arbitrary name but I've been banging my head trying to figure out what "Tout" is short for.

**Comment by bmuenzenmeyer** [comment]
It's a word: https://www.google.com/?ion=1&espv=2#q=define%20tout

**Comment by justinlevi** [comment]
Yeah, a google search is the first thing I did but the definition still didn't make sense to me as far as why that naming convention was chosen. 

I'm assuming it's based more on this context, am I correct? 

synonyms: peddle, sell, hawk, offer for sale, promote
"street merchants were touting their wares"

Is a Tout-list or a Tout-block commonly used in design circles these days?

# 

tout/
verb
1.
attempt to sell (something), typically by pestering people in an aggressive or bold manner.
"Jim was touting his wares"
2.
NORTH AMERICAN
offer racing tips for a share of any resulting winnings.
noun
1.
a person soliciting custom or business, typically in an aggressive or bold manner.
2.
NORTH AMERICAN
a person who offers racing tips for a share of any resulting winnings.
