### ISSUE TITLE
Duplicate key error in contact page

### ISSUE THREAD

**Issue by dagjaneiro** [pattern-lab/starterkit-mustache-demo#9]
A duplicate key error is stopping the contact page from properly compiling.

Ouput:

```
[14:24:06] Starting 'build'...
There was an error parsing sibling JSON for 04-pages/06-contact.mustache
{ YAMLException: duplicated mapping key at line 21, column 3:
```

**Comment by moda-schneij** [comment]
The JSON is fixed in the master branch but not in tag 4.0.2, which is what you get from a plain `npm install starterkit-mustache-demo`

**Comment by bmuenzenmeyer** [comment]
> plain npm install starterkit-mustache-demo

This package, like most PL packages, are moving to the @pattern-lab npm org

https://github.com/pattern-lab/starterkit-mustache-demo/blob/master/package.json#L2
https://www.npmjs.com/package/@pattern-lab/starterkit-mustache-demo

**Comment by Josh68** [comment]
I missed the namespace. Sorry about that. Thanks for the resopnse.
